import { RenderMode, ServerRoute } from '@angular/ssr';

export const serverRoutes: ServerRoute[] = [
  { path: '', renderMode: RenderMode.Prerender },
  { path: 'verify-email', renderMode: RenderMode.Prerender },
  { path: 'reset-password', renderMode: RenderMode.Prerender },
  { path: 'support', renderMode: RenderMode.Prerender },
  { path: 'support-volunteering-form', renderMode: RenderMode.Prerender },
  { path: 'care-rules', renderMode: RenderMode.Prerender },
  { path: 'adoption-rules', renderMode: RenderMode.Prerender },
  { path: 'social', renderMode: RenderMode.Prerender },
  {
    path: 'volunteer-application-confirmation',
    renderMode: RenderMode.Prerender,
  },
  { path: 'animals', renderMode: RenderMode.Prerender },
  { path: 'success-stories', renderMode: RenderMode.Prerender },
  { path: 'projects', renderMode: RenderMode.Prerender },
  { path: 'adoption', renderMode: RenderMode.Prerender },
  { path: 'about', renderMode: RenderMode.Prerender },
  { path: 'news', renderMode: RenderMode.Prerender },
  { path: 'terms-and-conditions', renderMode: RenderMode.Prerender },
  { path: 'privacy-policy', renderMode: RenderMode.Prerender },
  { path: 'public-offer', renderMode: RenderMode.Prerender },
  { path: 'reports', renderMode: RenderMode.Prerender },
  { path: 'contacts', renderMode: RenderMode.Prerender },
  { path: 'feedback-form', renderMode: RenderMode.Prerender },
  { path: 'payment/amount', renderMode: RenderMode.Prerender },
  { path: 'payment/details', renderMode: RenderMode.Prerender },
  { path: 'payment-status', renderMode: RenderMode.Prerender },
  { path: 'team', renderMode: RenderMode.Prerender },
  { path: 'access-denied', renderMode: RenderMode.Prerender },
  { path: 'internal-server-error', renderMode: RenderMode.Prerender },
  { path: 'service-unavailable', renderMode: RenderMode.Prerender },
  { path: 'adoption-applications-failed', renderMode: RenderMode.Prerender },

  { path: 'animals/:slug', renderMode: RenderMode.Server },
  { path: 'shelters/:slug', renderMode: RenderMode.Server },
  { path: 'shelters/:slug/animals', renderMode: RenderMode.Server },
  { path: 'projects/:slug', renderMode: RenderMode.Server },
  { path: 'news/:id', renderMode: RenderMode.Server },
  { path: 'search-results', renderMode: RenderMode.Server },
  { path: 'profile', renderMode: RenderMode.Server },
  { path: 'profile/edit', renderMode: RenderMode.Server },
  { path: 'profile/security', renderMode: RenderMode.Server },
  { path: 'profile/adoption-applications', renderMode: RenderMode.Server },
  { path: 'favorites', renderMode: RenderMode.Server },
  { path: 'my-payments', renderMode: RenderMode.Server },
  { path: 'guardianships', renderMode: RenderMode.Server },
  { path: 'payment', renderMode: RenderMode.Server },
  { path: '**', renderMode: RenderMode.Server },
];
